name: tmshub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.2.0
  auto_size_text: null
  cupertino_icons: ^1.0.2
  dio: null
  dotted_border: null
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.1
  flutter_downloader: ^1.11.6
  flutter_launcher_icons: 0.13.1
  flutter_map: ^5.0.0
  flutter_map_marker_cluster: null
  flutter_native_splash: 2.3.10
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  http: ^1.1.0
  image_picker: null
  intl: ^0.18.1
  latlong2: ^0.9.0
  loader_overlay: ^3.0.0
  location: ^5.0.3
  permission_handler: ^11.0.1
  provider: null
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/Logo1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/Logo1.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/Logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
